apiVersion: v1
kind: Service
metadata:
  name: restaurant-svc
  namespace: adeola-ns
spec:
  selector:
    app: restaurant
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 32410
  type: NodePort