apiVersion: v1
kind: Service
metadata:
  name: restaurant-svc
  namespace: adeola-ns
spec:
  selector:
    app: restaurant
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32410
  type: NodePort